language: go
script:
- cd src/avege && ./makeall.sh
deploy:
  provider: releases
  api_key:
    secure: qROlG3DcJ0KV4iucaggSGshDNZspXnL336bnsserCG0337wAmHT08sfdOZMHORZ4hmzNnMvoj1ImU7eW7v1JprphD3npf9jj0Ns/2zM2lydrXGAGcCF0Ec0r8b5ZLS9CKZ+0wftkfHXDThWxJvC7g01L52BsxIPfFqkCZIexMwGG3xAwxYnVP6CFJ7U9+dOzhGsjTG6UxvWb4eMZsM0oqa18aT1tMmuiYw/5Y4RpngKPl/BafiyriTLP88PoyY/SpJS3ttggymH5IXIbBGHzlNK6f5/Niz76TDhTtimH65xT/QgUrFJJMlMtbntraxYvwCBhgADM95AA7ncv0GKXiAJswnjPknVRzAtxRdUopY0Spblln0HjZuYjimbbmtv5OZaARgHK1/gQS8p2EGnsXzAFuY9asWGHlkayIxFYx1rQXwIMERrX4v6BwBqEK6ni6DwMxtlxF9rQvpZ2/Q8w/BzexEN8p1zQD784SS/UdWr2P81OsEH9wx+X8Z7Eyw4FM6XP6EMC+412xASLDhQwJK90ut7fME5BAOipgCx6rCaXlxm2e/XVNB6ZlB41mj42HmlvJzvi0i648yRtKHmqEv6Ff82LGET4PapT7OFES9MSZUupSr7NGocs4v8XGhrhL607ugJcC2qP5ZHy4eqGREImyYsdkv+T7lZazEuRe8s=
  file: avege-linux-amd64.tar.gz
  on:
    repo: missdeer/avege
