language: go
go:
  - tip
env:
  global:
      - NDK_VERSION=r13b
      - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
      - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

install:
  - >
    if [ ! -d "$ANDROID_NDK_HOME" ]; then
        mkdir -p $ANDROID_NDK_HOME;
        pushd $HOME/.android;
        export ARCH=`uname -m`;
        wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
        unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
        popd;
    fi
  - go get github.com/op/go-logging
  - go get github.com/garyburd/redigo/redis
  - go get github.com/go-fsnotify/fsnotify
  - go get github.com/kardianos/osext
  - go get github.com/gin-gonic/gin
  - go get github.com/gorilla/websocket
  - go get github.com/DeanThompson/ginpprof
  - go get github.com/miekg/dns
  - go get github.com/aead/chacha20
  - go get github.com/codahale/chacha20
  - go get github.com/dgryski/go-camellia
  - go get github.com/dgryski/go-idea
  - go get github.com/dgryski/go-rc2
  - go get github.com/patrickmn/go-cache
  - go get github.com/RouterScript/ProxyClient
  - go get github.com/ftrvxmtrx/fd
  - pwd && ls -l && cd src/avege && ./makeall.sh
script:
  - pwd && cd ../.. && go build dummy.go && cd src/avege
deploy:
  provider: releases
  api_key:
    secure: qROlG3DcJ0KV4iucaggSGshDNZspXnL336bnsserCG0337wAmHT08sfdOZMHORZ4hmzNnMvoj1ImU7eW7v1JprphD3npf9jj0Ns/2zM2lydrXGAGcCF0Ec0r8b5ZLS9CKZ+0wftkfHXDThWxJvC7g01L52BsxIPfFqkCZIexMwGG3xAwxYnVP6CFJ7U9+dOzhGsjTG6UxvWb4eMZsM0oqa18aT1tMmuiYw/5Y4RpngKPl/BafiyriTLP88PoyY/SpJS3ttggymH5IXIbBGHzlNK6f5/Niz76TDhTtimH65xT/QgUrFJJMlMtbntraxYvwCBhgADM95AA7ncv0GKXiAJswnjPknVRzAtxRdUopY0Spblln0HjZuYjimbbmtv5OZaARgHK1/gQS8p2EGnsXzAFuY9asWGHlkayIxFYx1rQXwIMERrX4v6BwBqEK6ni6DwMxtlxF9rQvpZ2/Q8w/BzexEN8p1zQD784SS/UdWr2P81OsEH9wx+X8Z7Eyw4FM6XP6EMC+412xASLDhQwJK90ut7fME5BAOipgCx6rCaXlxm2e/XVNB6ZlB41mj42HmlvJzvi0i648yRtKHmqEv6Ff82LGET4PapT7OFES9MSZUupSr7NGocs4v8XGhrhL607ugJcC2qP5ZHy4eqGREImyYsdkv+T7lZazEuRe8s=
  file: 
    - avege-android-armv7.tar.gz          
    - avege-android-x86.tar.gz            
    - avege-darwin-amd64.tar.gz           
    - avege-dragonflybsd-amd64.tar.gz     
    - avege-freebsd-amd64.tar.gz          
    - avege-freebsd-arm.tar.gz            
    - avege-freebsd-x86.tar.gz            
    - avege-linux-amd64.tar.gz            
    - avege-linux-arm64.tar.gz            
    - avege-linux-armv6.tar.gz            
    - avege-linux-armv7.tar.gz            
    - avege-linux-mips64.tar.gz           
    - avege-linux-mips64le.tar.gz         
    - avege-linux-ppc64.tar.gz            
    - avege-linux-ppc64le.tar.gz          
    - avege-linux-x86.tar.gz              
    - avege-netbsd-amd64.tar.gz           
    - avege-netbsd-arm.tar.gz             
    - avege-netbsd-x86.tar.gz             
    - avege-openbsd-amd64.tar.gz          
    - avege-openbsd-x86.tar.gz            
    - avege-solaris.tar.gz                
    - avege-win-amd64.tar.gz              
    - avege-win-x86.tar.gz                
  on:
    repo: missdeer/avege
    tags: true
  skip_cleanup: true